// 英文词条表：键 = 源码里 L.T("...") 中的中文原文（含 \n \t \" 等转义），值 = 英文译文。
// 由 tools\build-strings.ps1 从 tools\g*.en.txt 生成，请勿手改。
using System.Collections.Generic;

namespace AePluginManager
{
    internal static partial class Strings
    {
        public static Dictionary<string, string> All()
        {
            var map = new Dictionary<string, string>();
            AddUi(map);
            AddRules(map);
            AddCore(map);
            return map;
        }

        private static void Add(Dictionary<string, string> map, string zh, string en)
        {
            if (!string.IsNullOrEmpty(zh) && !map.ContainsKey(zh)) map[zh] = en;
        }

        private static void AddUi(Dictionary<string, string> map)
        {
            Add(map, "   路径穿越与越界写入会被拒绝并在日志中记录。\n\n", "   Path traversal and out-of-bounds writes are rejected and recorded in the log.\n\n");
            Add(map, "   且它只作用于本软件的备份区，不触碰 AE 目录。\n\n", "   It only affects this software's backup area and never touches the AE directories.\n\n");
            Add(map, "   唯一会真正删数据的是回收区里的\"彻底删除备份\"按钮，\n", "   The only feature that truly deletes data is the \"Delete Backup Permanently\" button in the Recycle Bin,\n");
            Add(map, "  （该版本的改动已全部回滚，AE 目录保持原样）", "  (all changes in that version were rolled back; the AE directories are unchanged)");
            Add(map, "  … 以及另外 ", "  ... and another ");
            Add(map, "  包内只有 macOS 安装包，无法安装到 Windows 版 AE", "  The package only contains a macOS installer, so it cannot be installed to Windows After Effects");
            Add(map, "  请选择要运行的安装器（★ 为推荐；向导由本软件拉起，不静默安装）：", "  Please select the installer to run (★ = recommended; the wizard is launched by this software, no silent install):");
            Add(map, "  这个包里有 {0} 个可安装的内容，请选择要装的版本（★ 为推荐）：", "  This package contains {0} installable items; please select the version to install (★ = recommended):");
            Add(map, "  这个包里有多个可安装的内容，请选择要装的版本：", "  This package contains multiple installable items; please select the version to install:");
            Add(map, "  这个包只有安装程序，请选择要运行的安装器（安装向导由本软件拉起，不静默安装）：", "  This package contains only installers; please select the installer to run (the installer wizard is launched by this software, no silent install):");
            Add(map, "　⚠ After Effects 正在运行", "　⚠ After Effects is running");
            Add(map, " 个", " item");
            Add(map, " 个 AE 版本", " AE version");
            Add(map, " 个（见「已安装插件」页）", " (see the \"Installed Plugins\" tab)");
            Add(map, " 个覆盖现有文件", " will overwrite existing files");
            Add(map, " 个失败", " failed");
            Add(map, " 更改为 ", " Change to ");
            Add(map, "（目录形式）", "(directory format)");
            Add(map, "（未勾选任何 AE 版本）", "(no AE version selected)");
            Add(map, "，其中 ", ", of which ");
            Add(map, "[shot] 安装器运行结果:\n", "[shot] Installer run result:\n");
            Add(map, "\n\n如果提示权限不足，请改用「以管理员身份运行安装器」。", "\n\nIf a permission error appears, run the \"Run Installer as Administrator\" option instead.");
            Add(map, "\n\n完成后可再点「重新检测」确认该项已消失。", "\n\nWhen it finishes, click \"Detect Again\" to confirm the item is gone.");
            Add(map, "\n\n原有备份仍留在旧位置，如需继续管理请手动迁移。", "\n\nThe existing backup remains in the old location; migrate it manually if you want to keep managing it.");
            Add(map, "{0}　[{1}]　{2}{3}\n     修改时间 {4}{5}", "{0}　[{1}]　{2}{3}\n     Modified {4}{5}");
            Add(map, "{0}　{1}　{2} 个条目", "{0}　{1}　{2} items");
            Add(map, "{0} 次卸载记录（共 {1} 个条目）", "{0} uninstall records ({1} items in total)");
            Add(map, "【{0}】\n\n{1}\n\n即将处理 {2} 个文件：\n{3}\n\n", "[{0}]\n\n{1}\n\nAbout to process {2} files:\n{3}\n\n");
            Add(map, "【安装方案】{0} 个文件，共 {1}", "[Install plan] {0} files, {1} in total");
            Add(map, "【修复方案】", "[Fix plan]");
            Add(map, "【需要运行安装向导】", "[Installer wizard required]");
            Add(map, "· 安装器把插件装到了 C:\\Program Files\\Adobe\\Common\\Plug-ins（共享目录，需要管理员权限）；", "· The installer placed plugins in C:\\Program Files\\Adobe\\Common\\Plug-ins (a shared directory that requires administrator rights);");
            Add(map, "· 安装器可能要求管理员权限（若提示失败，请改用「以管理员身份运行安装器」）；\n", "· The installer may require administrator rights (if it reports a failure, run the \"Run Installer as Administrator\" option instead);\n");
            Add(map, "· 安装器要求管理员权限但被拒绝。", "· The installer requires administrator rights but the request was denied.");
            Add(map, "· 安装向导会正常显示，请按向导操作；\n", "· The installer wizard will be displayed as usual; please follow it;\n");
            Add(map, "· 本软件不添加任何静默/隐藏参数，也不会替你点下一步；\n", "· This software adds no silent or hidden parameters and will not click Next for you;\n");
            Add(map, "· 你在向导里点了取消；", "· You clicked Cancel in the wizard;");
            Add(map, "· 装完后本软件会重新扫描 AE 目录，告诉你新增了哪些插件。\n\n是否继续？", "· After installation, this software will rescan the AE directories and tell you which plugins were added.\n\nContinue?");
            Add(map, "1. 只写入已发现的 AE 安装目录（Plug-ins / Scripts / Presets），\n", "1. It writes only to the detected AE installation directories (Plug-ins / Scripts / Presets),\n");
            Add(map, "2. 任何覆盖前都先备份原文件到数据目录，安装失败会自动整体回滚。\n\n", "2. Before any overwrite it backs up the original files to the data folder, and a failed install is rolled back entirely.\n\n");
            Add(map, "3. 没有\"删除\"功能：卸载是把文件移动到回收区，可一键还原。\n", "3. There is no \"delete\" feature: uninstalling moves files to the Recycle Bin, and they can be restored in one click.\n");
            Add(map, "AE 版本", "AE version");
            Add(map, "AE 插件管理器", "AE Plugin Manager");
            Add(map, "After Effects 正在运行，插件文件可能被占用导致写入失败。\n\n仍要继续吗？", "After Effects is running; plugin files may be locked and writes may fail.\n\nContinue anyway?");
            Add(map, "After Effects 正在运行，文件可能被占用。\n\n仍要继续吗？", "After Effects is running; files may be locked.\n\nContinue anyway?");
            Add(map, "After Effects 正在运行，文件可能被占用导致操作失败。\n\n仍要继续吗？", "After Effects is running; files may be locked and the operation may fail.\n\nContinue anyway?");
            Add(map, "安全说明", "Safety notes");
            Add(map, "安全说明(&S)", "Safety &notes(&S)");
            Add(map, "安装插件", "Install Plugin");
            Add(map, "安装程序不存在：", "Installer not found:");
            Add(map, "安装结果", "Install result");
            Add(map, "安装器运行结果", "Installer run result");
            Add(map, "安装完成，本次新增/更新了 {0} 个插件：", "Installation complete. {0} plugins were added or updated this time:");
            Add(map, "安装完成：{0} 个文件写入成功{1}。\n\n{2}\n", "Installation complete: {0} files written successfully{1}.\n\n{2}\n");
            Add(map, "安装向导已结束，但没有在 AE 插件目录里发现新文件。", "The installer wizard has closed, but no new files were found in the AE plugin directories.");
            Add(map, "按 Blender BLT 的使用思路设计：扫描纳管、冲突检测、拖入即装、可回滚。", "Designed around the Blender BLT workflow: scan and manage, conflict detection, drag in to install, and rollback support.");
            Add(map, "把「{0}」的 {1} 个条目还原到原位置？\n\n", "Restore \"{0}\" ({1} items) to their original locations?\n\n");
            Add(map, "把插件压缩包（.zip / .rar / .7z）、插件文件夹，或单个插件文件（.aex / .jsxbin / .jsx / .ffx）拖到这里\n", "Drag plugin archives (.zip / .rar / .7z), plugin folders, or individual plugin files (.aex / .jsxbin / .jsx / .ffx) here\n");
            Add(map, "把选中条目移入回收区", "Move the selected items to the Recycle Bin");
            Add(map, "把以下 {0} 个条目移入回收区？\n\n{1}\n\n", "Move the following {0} items to the Recycle Bin?\n\n{1}\n\n");
            Add(map, "版本 1.0\n\n", "Version 1.0\n\n");
            Add(map, "包内只有 .exe / .msi 安装器也可以：软件会列出安装器，由你确认后拉起安装向导（不静默安装）", "A package containing only .exe / .msi installers is fine too: the software lists the installers, and the installer wizard is launched after you confirm (no silent install)");
            Add(map, "保留这一份，其余移入回收区", "Keep this copy and move the rest to the Recycle Bin");
            Add(map, "备份位置由 ", "The backup location is set by ");
            Add(map, "被覆盖的文件会先备份到数据目录，可随时还原。是否继续？", "Overwritten files are first backed up to the data folder and can be restored at any time. Continue?");
            Add(map, "本机发现 {0} 个 AE 安装：\n{1}\n\n", "{0} AE installations found on this computer:\n{1}\n\n");
            Add(map, "本软件对 AE 安装目录的写操作遵守三条硬规则：\n\n", "This software follows three hard rules when writing to AE installation directories:\n\n");
            Add(map, "编解码插件", "Codec plugin");
            Add(map, "操作", "Actions");
            Add(map, "查看操作日志", "View operation log");
            Add(map, "查看关闭方法", "See how to close it");
            Add(map, "彻底删除「{0}」在备份区的数据？\n\n", "Permanently delete the data of \"{0}\" in the backup area?\n\n");
            Add(map, "彻底删除备份", "Delete Backup Permanently");
            Add(map, "冲突与不适用", "Conflicts & Incompatibilities");
            Add(map, "此外，本软件不会执行插件自带的 .exe/.msi 安装器——\n", "Also, this software will not run .exe/.msi installers bundled with plugins—\n");
            Add(map, "打开备份目录", "Open backup folder");
            Add(map, "打开数据目录（备份与回收区）", "Open data folder (backup and Recycle Bin)");
            Add(map, "打开所在目录", "Open containing folder");
            Add(map, "大小", "Size");
            Add(map, "等待安装向导结束…", "Waiting for the installer wizard to close...");
            Add(map, "方案就绪：{0} 个文件，{1}", "Plan ready: {0} files, {1}");
            Add(map, "覆盖 32 位旧版", "Overwrite 32-bit old version");
            Add(map, "覆盖（已备份）", "Overwrite (backed up)");
            Add(map, "更改备份位置…", "Change backup location...");
            Add(map, "共发现 {0} 个已安装条目，{1} 项问题（其中 {2} 项严重）{3}", "{0} installed items found, {1} issues ({2} critical){3}");
            Add(map, "关闭 After Effects", "Close After Effects");
            Add(map, "关于", "About");
            Add(map, "还没有操作日志", "No operation log yet");
            Add(map, "还原结果", "Restore result");
            Add(map, "还原位置：", "Restore to:");
            Add(map, "回收区", "Recycle Bin");
            Add(map, "级别", "Severity");
            Add(map, "即将把「{0}」安装到 {1} 个 AE 版本：\n  {2}\n\n共 {3} 个文件（{4}）{5}\n\n", "About to install \"{0}\" to {1} AE versions:\n  {2}\n\n{3} files in total ({4}){5}\n\n");
            Add(map, "即将运行安装程序：\n\n  {0}\n\n", "About to run the installer:\n\n  {0}\n\n");
            Add(map, "建议：", "Suggestions:");
            Add(map, "将安装到：{0}", "Will be installed to: {0}");
            Add(map, "将写入的位置", "Locations to be written");
            Add(map, "脚本", "Scripts");
            Add(map, "就绪", "Ready");
            Add(map, "开始安装（自动备份）", "Start Installation (auto backup)");
            Add(map, "可能的原因：", "Possible causes:");
            Add(map, "可以试试「以管理员身份运行安装器」，或点「重新扫描」后再看。", "Try \"Run Installer as Administrator\", or click \"Rescan\" and check again.");
            Add(map, "扩展", "Extensions");
            Add(map, "来源：", "Source:");
            Add(map, "类型", "Type");
            Add(map, "没有可运行的安装器", "No installer available to run");
            Add(map, "名称", "Name");
            Add(map, "名称：{0}\r\n类型：{1}{2}\r\n位置：{3}\r\n大小：{4}　修改时间：{5}\r\n", "Name: {0}\r\nType: {1}{2}\r\nLocation: {3}\r\nSize: {4}　Modified: {5}\r\n");
            Add(map, "那类插件请在安装向导中手动安装，再用本软件纳管。\n\n", "Install that kind of plugin manually in the installer wizard, then manage it with this software.\n\n");
            Add(map, "内容", "Contents");
            Add(map, "启动安装程序失败", "Failed to launch the installer");
            Add(map, "清空", "Clear");
            Add(map, "请先勾选要安装到的 AE 版本", "Please select the AE version to install to first");
            Add(map, "请先选择一条记录", "Please select a record first");
            Add(map, "请先选中一个问题", "Please select an issue first");
            Add(map, "请先在列表中选中一个问题", "Please select an issue in the list first");
            Add(map, "请先在上方选择要运行的安装器", "Please select the installer to run above first");
            Add(map, "请选择要保留的那一份，其余副本将被移入回收区（可随时还原）：", "Please select the copy to keep; the other copies will be moved to the Recycle Bin (they can be restored at any time):");
            Add(map, "请在上方选择安装器后点「运行选中的安装器」", "Please select an installer above, then click \"Run Selected Installer\"");
            Add(map, "取消", "Cancel");
            Add(map, "全部版本", "All versions");
            Add(map, "全部类型", "All types");
            Add(map, "如需撤销，请到「回收区」选择对应记录一键还原。", "To undo this, go to the \"Recycle Bin\", select the corresponding record, and restore it in one click.");
            Add(map, "软件(&F)", "&File(&F)");
            Add(map, "若原位置已有同名文件，将被回收区中的版本覆盖。", "If a file with the same name already exists in the original location, it will be overwritten by the version in the Recycle Bin.");
            Add(map, "扫描失败", "Scan failed");
            Add(map, "删除后无法再还原这些文件（AE 目录不受影响）。", "These files cannot be restored after deletion (the AE directories are not affected).");
            Add(map, "删除结果", "Delete result");
            Add(map, "涉及文件", "Files involved");
            Add(map, "涉及文件：", "Files involved:");
            Add(map, "生成安装方案失败", "Failed to generate install plan");
            Add(map, "时间", "Time");
            Add(map, "识别包名：", "Package name detected:");
            Add(map, "识别失败", "Detection failed");
            Add(map, "数据目录（备份 / 回收区 / 日志）：\n{2}\n\n", "Data folder (backup / Recycle Bin / log):\n{2}\n\n");
            Add(map, "数据目录：", "Data folder:");
            Add(map, "刷新", "Refresh");
            Add(map, "特效插件", "Effect plugin");
            Add(map, "提示", "Info");
            Add(map, "同一个插件存在多个副本时 After Effects 只会加载其中一个，具体加载哪个取决于目录扫描顺序。\n", "When a plugin has multiple copies, After Effects loads only one of them, and which one depends on the directory scan order.\n");
            Add(map, "退出", "Exit");
            Add(map, "未知", "Unknown");
            Add(map, "位数", "Bitness");
            Add(map, "位置", "Location");
            Add(map, "文件不会真正删除，可在「回收区」一键还原。", "The files are not really deleted and can be restored in one click from the \"Recycle Bin\".");
            Add(map, "文件数", "File count");
            Add(map, "问题", "Issue");
            Add(map, "无法启动安装程序", "Cannot launch the installer");
            Add(map, "显示 {0} / 共 {1}", "Showing {0} / {1}");
            Add(map, "写入前会自动备份被覆盖的文件；安装记录可在「回收区」一键还原。", "Overwritten files are backed up automatically before writing; install records can be restored in one click from the \"Recycle Bin\".");
            Add(map, "卸载到回收区", "Uninstall to Recycle Bin");
            Add(map, "卸载结果", "Uninstall result");
            Add(map, "新的备份位置：", "New backup location:");
            Add(map, "新增", "New");
            Add(map, "修复方案", "Fix plan");
            Add(map, "修复结果", "Fix result");
            Add(map, "修改时间", "Modified");
            Add(map, "选择备份与回收区的存放位置", "Choose where to store backups and the Recycle Bin");
            Add(map, "选择插件压缩包（也可直接拖入文件夹）", "Select plugin archive (you can also drag in a folder)");
            Add(map, "选择压缩包或文件夹…", "Select archive or folder...");
            Add(map, "选择要保留的副本 — ", "Select copies to keep — ");
            Add(map, "严重", "Critical");
            Add(map, "严重 {0} · 注意 {1} · 提示 {2}　可一键修复 {3} 项", "{0} critical · {1} warnings · {2} info　{3} items can be fixed in one click");
            Add(map, "一键还原", "Restore in one click");
            Add(map, "一键修复", "One-click Fix");
            Add(map, "一键修复：", "One-click Fix:");
            Add(map, "已安装插件", "Installed Plugins");
            Add(map, "已切换", "Switched");
            Add(map, "以管理员身份运行安装器", "Run Installer as Administrator");
            Add(map, "预设", "Presets");
            Add(map, "运行选中的安装器", "Run Selected Installer");
            Add(map, "在资源管理器中显示", "Show in File Explorer");
            Add(map, "这个安装器体积过大，没有解压出来。\n请先手动解压原压缩包后再运行。", "This installer is too large and was not extracted.\nPlease extract the original archive manually, then run it.");
            Add(map, "这个问题没有可操作的单个文件", "This issue has no individual file to act on");
            Add(map, "这些文件会被移动到回收区（不会真正删除），随时可以在「回收区」一键还原。是否继续？", "These files will be moved to the \"Recycle Bin\" (not really deleted) and can be restored from it in one click at any time. Continue?");
            Add(map, "这些文件已经可以在「已安装插件」页里管理了。", "These files can already be managed on the \"Installed Plugins\" tab.");
            Add(map, "这一项没有可自动执行的修复动作", "This item has no fix action that can be performed automatically");
            Add(map, "这一项没有需要处理的文件", "This item has no files to process");
            Add(map, "正在安装到 AE ", "Installing to AE ");
            Add(map, "正在扫描 AE 插件目录…", "Scanning AE plugin directories...");
            Add(map, "正在识别：", "Detecting:");
            Add(map, "至少需要保留一份", "At least one copy must be kept");
            Add(map, "重新检测", "Detect Again");
            Add(map, "重新扫描", "Rescan");
            Add(map, "重新扫描\tF5", "Rescan\tF5");
            Add(map, "注意", "Warning");
            Add(map, "状态", "Status");
        }

        private static void AddRules(Dictionary<string, string> map)
        {
            Add(map, "    … 以及另外 ", "    ... and ");
            Add(map, "    建议：", "    Advice: ");
            Add(map, "    修复方案：", "    Fix plan: ");
            Add(map, " 个", " more");
            Add(map, "。文件大小不一致，说明版本不同，AE 实际加载哪一个取决于目录扫描顺序。", ". File sizes differ, which means the versions are different; which one After Effects actually loads depends on the directory scan order.");
            Add(map, "\n（或直接用「安装插件」重新安装一次）", "\n(or just reinstall it with \"Install Plugin\")");
            Add(map, "\n\n建议手动把它移动到：", "\n\nWe recommend moving it manually to: ");
            Add(map, "{0} · {1} 个文件 · {2}{3}", "{0} · {1} files · {2}{3}");
            Add(map, "{0} 个安装残留文件", "{0} leftover files");
            Add(map, "{0} 个插件与 AE 位数不匹配", "{0} plugins with a bitness mismatch");
            Add(map, "{0} 个非插件文件", "{0} non-plugin files");
            Add(map, "{0}：{1} 个文件", "{0}: {1} files");
            Add(map, "⚠ 其中 {0} 个文件会覆盖同名文件（覆盖前自动备份，可一键还原）", "⚠ {0} of these files will overwrite files with the same name (they are backed up automatically before overwriting and can be restored in one click)");
            Add(map, "⚠ 位数不匹配，装在 64 位 AE 上不会被加载：", "⚠ Bitness mismatch; they will not be loaded in 64-bit AE:");
            Add(map, "AE {0}：\"{1}\" 存在 {2} 个副本", "AE {0}: \"{1}\" has {2} copies");
            Add(map, "AE {0}：{1} 个特效插件文件放在了 Scripts 目录", "AE {0}: {1} effect plugin files are in the Scripts folder");
            Add(map, "After Effects 正在运行", "After Effects is running");
            Add(map, "After Effects 只会从 Plug-ins 目录加载 .aex/.8bf。放在 Scripts 里的文件不会被加载，", "After Effects only loads .aex/.8bf from the Plug-ins folder. Files placed in Scripts are not loaded, ");
            Add(map, "Plug-ins 下没有同名文件，直接删除会让这个插件彻底不可用，因此不提供一键操作：\n  ", "There is no file with the same name under Plug-ins, so deleting it outright would make the plugin completely unusable; therefore no one-click action is offered:\n  ");
            Add(map, "安装残留", "Leftover files");
            Add(map, "安装完成后回到本窗口点「重新扫描」，新装的插件就会出现在「已安装插件」里。", "When the installation is complete, return to this window and click \"Rescan\"; the newly installed plugins will appear on the \"Installed Plugins\" tab.");
            Add(map, "包内只有 macOS 安装包", "The package contains only a macOS installer");
            Add(map, "包内只有 macOS 安装包（.dmg/.pkg），无法安装到 Windows 版 AE。", "The package contains only a macOS installer (.dmg/.pkg), so it cannot be installed to the Windows version of AE.");
            Add(map, "包内只有安装程序（.exe/.msi），需要运行安装向导", "The package contains only installers (.exe/.msi); the installer wizard must be run");
            Add(map, "保留一份，其余移入回收区；保留哪一份由你决定。", "Keep one copy and move the rest to the Recycle Bin; which one to keep is up to you.");
            Add(map, "本软件不会强制结束 AE 进程（可能让你丢失未保存的工程）。\n", "This software will not force-quit the AE process (that could lose unsaved projects).\n");
            Add(map, "不支持的文件类型：", "Unsupported file types: ");
            Add(map, "部分破解补丁会把旧版插件改名成 .bak 留在原地，长期堆积后难以判断哪个是生效版本。", "Some crack patches rename the old plugin to .bak and leave it in place, so after a while it is hard to tell which copy is the active version.");
            Add(map, "插件更新或卸载后留下的 .bak/.old/.tmp 备份文件。它们不会被 AE 加载，只会让插件目录变乱，", "Backup files (.bak/.old/.tmp) left behind after a plugin update or uninstall. AE does not load them; they only make the plugin folder messy, ");
            Add(map, "查看关闭方法", "See how to close it");
            Add(map, "但如果 Plug-ins 里存在同名文件，两个副本的不同版本会造成\"装了却没生效\"或随机加载旧版的现象。", "but if a file with the same name exists in Plug-ins, the differing versions of the two copies can cause \"installed but not working\" or an old version being loaded at random.");
            Add(map, "典型现象：插件装在 Plug-ins 里，效果菜单里却找不到。", "Typical symptom: the plugin is installed in Plug-ins but does not appear in the Effects menu.");
            Add(map, "点「选择保留哪一份…」会列出全部副本的大小与修改时间，你挑一个保留，其余的移入回收区（可还原）。", "Clicking \"Choose the copy to keep...\" lists the size and modification time of every copy; keep one and the rest are moved to the Recycle Bin (restorable).");
            Add(map, "放错目录", "Wrong folder");
            Add(map, "附带依赖目录「{0}」", "Includes dependent folder \"{0}\"");
            Add(map, "根目录", "Root folder");
            Add(map, "根目录（含全部内容）", "Root folder (including all contents)");
            Add(map, "关闭 After Effects 后重新扫描。", "Close After Effects and rescan.");
            Add(map, "官方教程", "official tutorial");
            Add(map, "广告", "ads");
            Add(map, "汉化", "Chinese localization");
            Add(map, "检测到 AfterFX 进程。安装/卸载会改写插件目录，AE 运行时可能占用文件导致写入失败，", "An AfterFX process was detected. Installing/uninstalling rewrites the plugin folders, and while AE is running it may hold files open and cause write failures, ");
            Add(map, "简体", "Simplified");
            Add(map, "将把 {0} 个文件移入回收区（可还原）：\n  {1}", "About to move {0} files to the Recycle Bin (restorable):\n  {1}");
            Add(map, "教程", "tutorial");
            Add(map, "可安全移入回收区。", "They can be safely moved to the Recycle Bin.");
            Add(map, "来源：{0}", "Source: {0}");
            Add(map, "路径不存在：", "Path does not exist: ");
            Add(map, "没有可用的 AE 版本", "No AE version available");
            Add(map, "破解补丁", "crack");
            Add(map, "且 AE 退出时会回写插件缓存。建议先关闭 AE 再执行安装或卸载。", "and AE writes its plugin cache back when it exits. Close AE before installing or uninstalling.");
            Add(map, "请点击下方「打开所在目录」，双击安装器按向导安装；装完回到本软件重新扫描即可纳管。", "Click \"Open containing folder\" below, double-click the installer and follow the wizard; when it finishes, return to this software and rescan to bring it under management.");
            Add(map, "请在 AE 里保存工程后正常退出，再回到本软件点「重新检测」。", "Save your project in AE and exit normally, then return to this software and click \"Detect Again\".");
            Add(map, "确认 Plug-ins 下已有可用副本后，把 Scripts 里的多余副本移入回收区。", "After confirming that a usable copy exists under Plug-ins, move the extra copies in Scripts to the Recycle Bin.");
            Add(map, "如果这个包确实不含以上内容，请确认下载是否完整。", "If this package really contains none of the above, check that the download is complete.");
            Add(map, "若运行时提示权限不足，请改用「以管理员身份运行安装器」按钮。", "If a permission error appears while it runs, use the \"Run Installer as Administrator\" button instead.");
            Add(map, "识别到载荷文件，但无法映射到 AE 的安装目录（扩展名不在支持范围内）", "A payload file was detected, but it cannot be mapped to an AE installation directory (the extension is not supported)");
            Add(map, "使用教程", "usage tutorial");
            Add(map, "视频教程", "video tutorial");
            Add(map, "说明：安装器可能尝试写入 C:\\Program Files\\Adobe\\Common\\Plug-ins（需要管理员权限）。", "Note: the installer may try to write to C:\\Program Files\\Adobe\\Common\\Plug-ins (administrator rights required).");
            Add(map, "提示", "Info");
            Add(map, "同版本重复", "Duplicates in one version");
            Add(map, "同一版本内出现同名插件的多个副本：", "Several copies of the same plugin exist within one version: ");
            Add(map, "未在包内找到可安装的插件文件", "No installable plugin files were found in the package");
            Add(map, "位数不匹配", "Bitness mismatch");
            Add(map, "下载对应的 64 位版本重新安装；旧副本移入回收区。", "Download the matching 64-bit version and reinstall; move the old copy to the Recycle Bin.");
            Add(map, "选择保留哪一份…", "Choose the copy to keep...");
            Add(map, "严重", "Critical");
            Add(map, "移入回收区（清理不适用插件）", "Move to Recycle Bin (clean up inapplicable plugins)");
            Add(map, "移入回收区（清理残留）", "Move to Recycle Bin (clean up leftovers)");
            Add(map, "移入回收区（清理错位文件）", "Move to Recycle Bin (clean up misplaced files)");
            Add(map, "已安装条目：{0} 个；问题：{1} 项（严重 {2} / 注意 {3} / 提示 {4}）", "Installed items: {0}; issues: {1} (Critical {2} / Warning {3} / Info {4})");
            Add(map, "已选安装版本：{0}（共 {1} 个可选）", "Selected version to install: {0} ({1} available)");
            Add(map, "已自动排除 {0} 个非插件文件（教程视频/图片/网址/安装器/说明文档等）", "Automatically excluded {0} non-plugin files (tutorial videos/images/URLs/installers/documentation, etc.)");
            Add(map, "以及 .exe/.msi 安装程序（本软件可以拉起安装向导）。\n", "as well as .exe/.msi installers (this software can launch the installer wizard).\n");
            Add(map, "英文", "English");
            Add(map, "运行状态", "Running status");
            Add(map, "在压缩包内（体积过大未解压）", "Inside the archive (too large, not extracted)");
            Add(map, "找到的安装程序：", "Installers found:");
            Add(map, "这个包里没有可直接复制的插件文件，只有安装程序（安装器会自己把 .aex 写到 AE 插件目录）。", "This package contains no plugin files that can be copied directly, only installers (the installer writes the .aex files into the AE plugin folder itself).");
            Add(map, "这个插件在 AE {0} 里有 {1} 个副本，软件不替你决定保留哪个（哪份更新、哪份是你想要的，只有你知道）。\n", "In AE {0}, this plugin has {1} copies; this software will not decide for you which one to keep (only you know which one is newer or which one you want).\n");
            Add(map, "这是一个安装程序，不是可直接复制的插件包", "This is an installer, not a plugin package that can be copied directly");
            Add(map, "这些插件是 32 位（或 ARM）二进制，而 AE CC 2019 之后只有 64 位版本，加载时会被静默忽略。", "These plugins are 32-bit (or ARM) binaries, while AE has only 64-bit versions from CC 2019 onward, so they are silently ignored when loaded.");
            Add(map, "这些文件不会被 AE 加载，将移入回收区（可还原）：\n  {0}", "These files are not loaded by AE and will be moved to the Recycle Bin (restorable):\n  {0}");
            Add(map, "这些文件在 64 位 AE 上永远不会被加载，将移入回收区（可还原）：\n  {0}", "These files will never be loaded by 64-bit AE and will be moved to the Recycle Bin (restorable):\n  {0}");
            Add(map, "支持的类型：.aex/.8bf 特效插件、.jsx/.jsxbin 脚本、.ffx 预设、.plugin 编解码插件，\n", "Supported types: .aex/.8bf effect plugins, .jsx/.jsxbin scripts, .ffx presets, .plugin codec plugins,\n");
            Add(map, "支持的类型：.aex/.8bf 特效插件、.jsx/.jsxbin 脚本、.ffx 预设、.plugin 编解码插件。", "Supported types: .aex/.8bf effect plugins, .jsx/.jsxbin scripts, .ffx presets, .plugin codec plugins.");
            Add(map, "支持拖入：.zip / .rar / .7z 压缩包、文件夹，或单个 .aex/.jsxbin/.jsx/.ffx 文件。", "Drag and drop supported: .zip / .rar / .7z archives, folders, or a single .aex/.jsxbin/.jsx/.ffx file.");
            Add(map, "中文", "Chinese");
            Add(map, "中英", "Chinese + English");
            Add(map, "注意", "Warning");
            Add(map, "自带安装向导的插件（.exe/.msi）本软件不代为执行，以免静默写入注册表、系统目录或捆绑其他组件。\n", "For plugins with their own installer wizard (.exe/.msi), this software will not run them for you, to avoid silent writes to the registry or system folders or bundled third-party components.\n");
        }

        private static void AddCore(Dictionary<string, string> map)
        {
            Add(map, "   ← 覆盖现有文件", "   ← Overwrite existing file");
            Add(map, "　（体积过大，未解压）", "　(too large, not extracted)");
            Add(map, " 等 ", " and ");
            Add(map, " 个 AE 安装：", " AE installations:");
            Add(map, " 个失败", " failures");
            Add(map, " 个条目　", " items　");
            Add(map, " 个文件，", " files, ");
            Add(map, " 项", " items");
            Add(map, " 项备份数据", " backup items");
            Add(map, "　中文版", "　Chinese version");
            Add(map, "（现有为", "(existing: ");
            Add(map, "（已整体回滚，AE 目录保持原样）", "(fully rolled back; the AE folders are unchanged)");
            Add(map, "[{0}] {1} · {2} 个文件 · {3}", "[{0}] {1} · {2} files · {3}");
            Add(map, "[shot] 开始 outDir=", "[shot] start outDir=");
            Add(map, "[shot] 失败: ", "[shot] failed: ");
            Add(map, "{0}　{1}　{2}　{3} 个条目　{4}", "{0}　{1}　{2}　{3} items　{4}");
            Add(map, "【安装方案】共 ", "[Install plan] ");
            Add(map, "【说明】", "[Notes]");
            Add(map, "【需要人工安装】", "[Manual installation required]");
            Add(map, "⚠ 压缩包解压量过大，已提前停止", "⚠ The archive's extracted size is too large; stopped early");
            Add(map, "32 位", "32-bit");
            Add(map, "64 位", "64-bit");
            Add(map, "AE插件管理器", "AE Plugin Manager");
            Add(map, "安装", "Install");
            Add(map, "安装失败并已回滚：", "Installation failed and was rolled back: ");
            Add(map, "安装完成：{0} 个文件（{1}）已写入 AE {2}{3}", "Installation complete: {0} files ({1}) written to AE {2}{3}");
            Add(map, "包名：", "Package name: ");
            Add(map, "保存会话清单失败：", "Failed to save session manifest: ");
            Add(map, "本软件不尝试破解或询问压缩包密码。\n", "This software does not try to crack archives or ask for their passwords.\n");
            Add(map, "本软件通过以下位置查找 AE：\n", "This software looks for AE in the following locations:\n");
            Add(map, "编解码插件", "Codec plugin");
            Add(map, "常见原因：有密码、文件损坏、CRC 校验失败。请手动解压后把文件夹拖进本软件。", "Common causes: a password, a damaged file, or a CRC check failure. Please extract it manually, then drag the folder into this software.");
            Add(map, "彻底删除失败：", "Permanent delete failed: ");
            Add(map, "打开目录失败：", "Failed to open folder: ");
            Add(map, "打开失败：", "Failed to open: ");
            Add(map, "读取会话清单失败：", "Failed to read session manifest: ");
            Add(map, "发现 ", "Found ");
            Add(map, "覆盖", "Overwrite");
            Add(map, "共享插件目录（只读检测）：", "Shared plug-ins folder (read-only check):");
            Add(map, "还原 ", "Restore ");
            Add(map, "还原失败：", "Restore failed: ");
            Add(map, "回滚失败：", "Rollback failed: ");
            Add(map, "会话 ", "Session ");
            Add(map, "检测对象：", "Detection target: ");
            Add(map, "建议：用你现有的解压软件（WinRAR / 7-Zip / Bandizip）解压到任意文件夹，\n", "Suggestion: extract it to any folder with your existing extraction tool (WinRAR / 7-Zip / Bandizip),\n");
            Add(map, "脚本", "Script");
            Add(map, "结果：", "Result: ");
            Add(map, "截图失败：", "Screenshot failed: ");
            Add(map, "解压 {0} 个文件（{1}），跳过 {2} 个非插件文件（{3}）", "Extracted {0} files ({1}), skipped {2} non-plugin files ({3})");
            Add(map, "解压超时（超过 10 分钟）", "Extraction timed out (over 10 minutes)");
            Add(map, "拒绝操作 AE 目录之外的条目：", "Refused to operate on an item outside the AE folders: ");
            Add(map, "拒绝操作：该路径不在已发现的 AE 安装目录内。", "Refused: that path is not inside a detected AE installation folder.");
            Add(map, "拒绝写入 AE 目录之外的目标：", "Refused to write a target outside the AE folders: ");
            Add(map, "开始安装 {0} 到 AE {1}，共 {2} 个文件", "Starting installation of {0} to AE {1}, {2} files in total");
            Add(map, "扩展", "Extension");
            Add(map, "路径不存在：", "Path does not exist: ");
            Add(map, "路径无效：", "Invalid path: ");
            Add(map, "没有需要复制的文件", "No files need to be copied");
            Add(map, "没有选中任何条目", "No items selected");
            Add(map, "没有找到 AE ", "No AE found for ");
            Add(map, "没有找到 AE 安装", "No AE installation found");
            Add(map, "没有找到会话 ", "No session found: ");
            Add(map, "没有找到任何 After Effects 安装。\n\n", "No After Effects installation was found.\n\n");
            Add(map, "目标：AE ", "Target: AE ");
            Add(map, "目标版本：AE ", "Target version: AE ");
            Add(map, "其他", "Other");
            Add(map, "请用解压软件输入密码解压后，把文件夹拖进本软件。", "Enter the password in your extraction tool to unpack the archive, then drag the folder into this software.");
            Add(map, "然后把这个文件夹直接拖进本软件窗口。", "then drag that folder straight into this software's window.");
            Add(map, "使用外部解压工具：", "Using an external extraction tool: ");
            Add(map, "使用系统自带解压组件（bsdtar / libarchive）", "Using the built-in extraction component (bsdtar / libarchive)");
            Add(map, "数据目录：", "Data folder: ");
            Add(map, "特效插件", "Effect plugin");
            Add(map, "未知", "Unknown");
            Add(map, "无法解压这个压缩包", "Cannot extract this archive");
            Add(map, "系统自带解压组件不支持该压缩包（常见于加密包或损坏包）。\n", "The built-in extraction component does not support this archive (common with encrypted or damaged archives).\n");
            Add(map, "写入报告失败: ", "Failed to write report: ");
            Add(map, "写入会话清单失败：", "Failed to write session manifest: ");
            Add(map, "写入失败：", "Write failed: ");
            Add(map, "卸载", "Uninstall");
            Add(map, "卸载：", "Uninstall: ");
            Add(map, "卸载失败：", "Uninstall failed: ");
            Add(map, "新增", "New");
            Add(map, "压缩包解压失败（WinRAR 返回 ", "Archive extraction failed (WinRAR returned ");
            Add(map, "压缩包可能过大或已损坏。请手动解压后把文件夹拖进本软件。", "The archive may be too large or damaged. Please extract it manually, then drag the folder into this software.");
            Add(map, "压缩包内文件名使用 GBK 编码（未标记 UTF-8），已按系统码页正确解码", "File names in the archive use GBK encoding (not marked as UTF-8) and were decoded correctly with the system code page");
            Add(map, "压缩包已加密，需要密码", "The archive is encrypted and needs a password");
            Add(map, "移入回收区：", "Move to Recycle Bin: ");
            Add(map, "已彻底删除 ", "Permanently deleted ");
            Add(map, "已还原 {0} 个条目{1}", "Restored {0} items{1}");
            Add(map, "已还原：", "Restored: ");
            Add(map, "已移入回收区：{0} 个条目{1}（可随时一键还原）", "Moved to Recycle Bin: {0} items{1} (can be restored at any time with one click)");
            Add(map, "以及注册表登记的安装路径。", "and the installation paths registered in the registry.");
            Add(map, "有 {0} 个文件写入失败（常见原因：AE 正在运行占用文件、或没有管理员权限），已把本次改动全部还原。", "Failed to write {0} files (common causes: AE is running and holding the files, or no administrator rights); all changes from this run were rolled back.");
            Add(map, "预设", "Preset");
            Add(map, "发现 {0} 个 AE 安装：", "Found {0} After Effects installations:");
        }

    }
}
